# Generated by Django 4.2.5 on 2023-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
